language: python
# os:
#     - linux
#     - osx
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - "pip install -r requirements.txt"
    - "pip install ."
    - "pip install pytest"
    - "pip install pytest-cov"
    # - "pip install coverage"
    - "pip install coveralls"
script:
    - "pytest"
    # - "coverage run --source=Afvalwijzer setup.py test"
    - "py.test --cov-report term-missing --cov=Afvalwijzer tests/"
after_success: coveralls
