language: python
os: linux
# sudo: false
python:
    - "3.5"
    - "3.6"
install:
    - "pip install -r requirements.txt"
    # - "pip install coverage"
    # - "pip install coveralls"
script:
    - "coverage run --source=Afvalwijzer setup.py test"
after_sucess:
    coveralls
